OJ/urls.py
from django.contrib import admin
from django.urls import include, path

admin.site.site_header = "OJ Admin"
admin.site.site_title = "OJ Admin Portal"
admin.site.index_title = "Welcome to OJ admin"

urlpatterns = [
    path('practice/', include('practice.urls')),
    path('admin/', admin.site.urls),
]

practice/urls.py
from django.urls import path
from . import views

app_name = 'practice'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:problemid>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    #path('<int:problemid>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:problemid>/submit/', views.submit, name='submit'),
    #Leaderboard
    path('leaderboard/', views.leaderboard, name = 'leaderboard'),
    #Login
    path('login/', views.login, name = 'login'),
    #logout
    path('logout/', views.logoutUser, name = 'logout'),
    #register
    path('register/', views.register, name = 'register')
]

practice/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class User(models.Model):
    Firstname=models.CharField(max_length=20)
    Lastname=models.CharField(max_length=20)
    email=models.EmailField(max_length=50)
    password=models.CharField(max_length=30)

    def __str__(self):
        return self.Firstname


class Problem(models.Model):
   problemid=models.CharField(("ID"), max_length=50)
   problemname=models.CharField(("name"), max_length=50)
   description=models.CharField(max_length=300)
   score=models.IntegerField(default=0)

   def __str__(self):
       return str(self.problemid) + " " +self.problemname

class Submission(models.Model):
    problemid=models.ForeignKey(Problem, on_delete=models.CASCADE)
    answercode=models.CharField(max_length=300)
    submissiontime=models.TimeField(default=timezone.now)
    verdict=models.CharField(max_length=20)
  
    def __str__(self):
       return str(self.problemid) + str(self.submissiontime)

class Testcase(models.Model):
    problemid=models.ForeignKey(Problem,on_delete=models.CASCADE)
    inputdoc=models.CharField(max_length=500)
    outputdoc=models.CharField(max_length=500)

    def __str__(self):
       return str(self.problemid)

practice/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

practice/views.py
from django.shortcuts import get_object_or_404, redirect,render
from django.http import HttpResponse,Http404,HttpResponseRedirect
from django.utils import timezone
import subprocess,os,sys
from django.contrib.auth.forms import UserCreationForm
import os.path
from .models import Problem,Testcase,Submission
from .forms import CreateUserForm
from django.contrib.auth import authenticate, login as auth_login, logout

from django.contrib import messages
from django.contrib.auth.decorators import login_required

#@login_required(login_url='practice:login')
def index(request):
    Problem_list = Problem.objects.order_by('problemid')
    context = {'Problem_list': Problem_list}
    return render(request, 'practice/index.html', context)

@login_required(login_url='practice:login')
def detail(request, problemid):
    problem = get_object_or_404(Problem, pk=problemid)
    return render(request, 'practice/detail.html', {'problem': problem})

def login(request):
    if request.user.is_authenticated:
        return redirect('practice:home')
    
    else:    
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)
            if user is not None:
                auth_login(request, user)
                return redirect('practice:index')

            else:
                messages.info(request, 'Username or password is incorrect')

        context = {}
        return render(request, 'practice/login.html', context)

def register(request):
    if request.user.is_authenticated:
        return redirect('practice:home')
    
    else:
        form = CreateUserForm()

        if request.method == 'POST':
            form = CreateUserForm(request.POST)
            if form.is_valid():
                form.save()
                user = form.cleaned_data.get('username')
                messages.success(request, 'Account was created for ' + user)

                return redirect('practice:login')

        context = {'form':form}
        return render(request, 'practice/register.html', context)

def logoutUser(request):
    logout(request)
    return redirect('practice:login')

@login_required(login_url='practice:login')
def leaderboard(request):
    recent_submissions = Submission.objects.all().order_by('-submissiontime')[:10]
    return render(request, 'practice/leaderboard.html', {"solutions": recent_submissions})

def submit(request, problemid):
    input=Testcase.objects.get(pk=problemid).inputdoc
    output=Testcase.objects.get(pk=problemid).outputdoc
  
#We can Store the submitted file in this path with dynamic name (problemid)
    temp = r"D:\Django Projects\codersOJ\Submissions\%s"%problemid + ".cpp" 
    
    #creating the submission file
    code_file=open(temp,'wb+') 


    code=request.POST.get('code')
    #we need to convert the code that we get from form to bytes to use the write command
    code=bytes(code,'utf-8')
    code_file.write(code)
    
    #now in the submission file the text is copied from code , we need to convert it to bytes to allow subprocess to run it
    code_file=bytes(temp,'utf-8')
    
    
    #if there is a problem while compiling we set the verdict as compilation error
    compile=subprocess.run(["g++",temp],shell=True)
    verdict=""

    if(compile.returncode!=0):
        verdict="Compilation Error"

    expected_output=open(output,'r').read()

    input_file=open(input,'r')

    process = subprocess.run('a.exe', stdin=input_file,shell=True, capture_output=True,text=True)
     
    
    user_output= process.stdout.strip()


    # we need to check if there was a problem in compiling the submitted code as even after compilation error there might be previous "a.exe" file of previous code available in the system
    if(process.returncode!=0 ):
        verdict="Compilation Error"
    elif(expected_output==user_output and verdict!="Compilation Error"):
        verdict="Answer Correct"
    elif(verdict!="Compilation Error"):
        verdict="Wrong answer"
    
    submission=Submission()
    temp=str(temp)

    submission.problemid=Problem.objects.get(pk=problemid)
    submission.answercode=temp
    submission.verdict=verdict
    submission.save()

    
    # return HttpResponse("Your Anwer verdict is %s." % verdict)
    return redirect('practice:leaderboard')


    
    


    

practice/templates/practice/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
      {%if title %}
        <title>Practice|{{title}}</title>
      {%else%}
        <title>Practice</title>
      {%endif%}

      <span id="hello-msg">Hello, {{request.user}}</span>
      <span><a href={%url 'practice:logout' %}>Logout</a></span>
  </head>
  <body>
    <nav class ="navbar navbar-dark bg-primary mb-4">
        <div class ="container">
            <a class ="navbar-brand" href ="/practice">Problem List</a>
        </div>
    </nav>
    <div class="container">
      <div class="row">
        <div class="col-md-6 m-auto">
          {% block content %}{% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

practice/templates/practice/detail.html
{% extends 'practice/base.html' %}

{% block content %}
<div class="card">
    <div class="card-body">
        <h4>{{problem.problemname}}</h4>
        <p class="card-text">{{problem.description}}</p>
    </div>
</div>

<form action='{% url 'practice:submit' problem.problemid %}' method="POST">
{% csrf_token %}
        <fieldset>
          <div class="form-group">
            <textarea <input type="text" name="code" id="code" class="form-control" rows="20" ></textarea>
          </div>
          <div class="form-group">
            <label >Select Language</label>
            <select name="language" id="language" class="form-select">
              <option >C++</option>
            </select>
          </div> 
          <button type="submit" class="btn btn-primary">Submit</button>
        </fieldset>  
</form>

{% endblock %}

practice/templates/practice/index.html
{% extends 'practice/base.html' %}

{% block content %}

{% if Problem_list %}
    <ul>
    {% for problem in Problem_list %}
        <li><a href="{% url 'practice:detail' problem.problemid %}">{{ problem.description }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

{% endblock %}

practice/templates/practice/leaderboard.html
{% extends 'practice/base.html'%}

{% block content%}
<table class="table" class="table-responsive">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Probid</th>
        <th scope="col">Verdict</th>
        <th scope="col">submissiontime</th>
      </tr>
    </thead>
    <tbody>
        {%for solution in solutions%}
        <tr>
            <td>{{solution.problemid}}</td>
            <td>{{solution.verdict}}</td>
            <td>{{solution.submissiontime}}</td>
        </tr>
        {% endfor %} 
    </tbody>
  </table>
   
{%endblock%}

practice/templates/practice/login.html
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>

				{% for message in messages %}
					<p id="messages">{{message}}</p>
				{% endfor %}
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'practice:register' %}" class="ml-2">Sign Up</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>

practice/templates/practice/register.html
<html>
    
<head>
	<title>Register</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
		}
		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">REGISTER ACCOUNT</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{form.username}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							{{form.email}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password1}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password2}}
						</div>

				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Register Account">
				   		</div>
					</form>
				</div>
				
				{{form.errors}}
				
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Already have an account? <a href="{% url 'practice:login' %}" class="ml-2">Login</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field 
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Username..';
		form_fields[2].placeholder='Email..';
		form_fields[3].placeholder='Enter password...';
		form_fields[4].placeholder='Re-enter Password...';


		for (var field in form_fields){	
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
</html>